### ISSUE TITLE
error¿?

### ISSUE THREAD

**Issue by zephirusgit** [XuweiyiChen/UniCtrl#2]
i try install it in windows, but say me a error. 
after
 git clone https://huggingface.co/runwayml/stable-diffusion-v1-5 models/StableDiffusion/

i test and say
(animatediff_pt2) PS G:\ia\UniCtrl-main\examples\AnimateDiff> python app.py
### Cleaning cached examples ...
loaded 3D unet's pretrained weights from ./models/StableDiffusion\unet ...
### Motion Module Parameters: 417.1376 M
Traceback (most recent call last):
  File "G:\ia\UniCtrl-main\examples\AnimateDiff\app.py", line 536, in <module>
    controller = AnimateController()
  File "G:\ia\UniCtrl-main\examples\AnimateDiff\app.py", line 292, in __init__
    self.update_base_model(self.base_model_list[-2])
IndexError: list index out of range
(animatediff_pt2) PS G:\ia\UniCtrl-main\examples\AnimateDiff>

**Comment by TianX-IA** [comment]
I guess it's because you didn't download any of the peronalized T2I checkpoints. I have fixed this issue in the new version. However, if you want to run the examples in the code, you still need to [download the RealisticVision checkpoint](https://github.com/XuweiyiChen/UniCtrl?tab=readme-ov-file#3-download-checkpoints).
